/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;

import java.sql.ResultSet; 
import java.sql.SQLException; 
import java.util.ArrayList; 
import java.util.List; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JButton; 
import javax.swing.JComboBox; 
import javax.swing.JOptionPane; 
import javax.swing.JTable; 
import javax.swing.JTextField; 
import javax.swing.table.DefaultTableModel; 
import pack.control.c_koneksi; 
import pack.control.controllerToko; 
import pack.model.m_toko; 

/**
 *
 * @author Qoriatul Masfufah
 */
public class home extends javax.swing.JFrame {
    controllerToko ctoko;
    List<m_toko>listdata = new ArrayList<>();

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        ctoko = new controllerToko (this);
        ctoko.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtadmin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtkode = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        cbKategoriBrg = new javax.swing.JComboBox<>();
        cbjenis = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        Btn_Keluar = new javax.swing.JButton();
        Btn_Simpan = new javax.swing.JButton();
        Btn_Ubah = new javax.swing.JButton();
        Btn_Bersihkan = new javax.swing.JButton();
        Btn_Hapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CbCariKategori = new javax.swing.JComboBox<>();
        Btn_Cari = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Admin Toko:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 80, 30);

        txtadmin.setEditable(false);
        jPanel1.add(txtadmin);
        txtadmin.setBounds(110, 20, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Data Barang di Toko");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 20, 220, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 80);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Kode Barang");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 20, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Harga");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 180, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nama Barang");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 60, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Kategori Barang");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 100, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Jenis Packaging");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 140, 110, 30);
        jPanel2.add(txtharga);
        txtharga.setBounds(160, 180, 370, 30);
        jPanel2.add(txtkode);
        txtkode.setBounds(160, 20, 370, 30);
        jPanel2.add(txtnama);
        txtnama.setBounds(160, 60, 370, 30);

        cbKategoriBrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Baranglain" }));
        jPanel2.add(cbKategoriBrg);
        cbKategoriBrg.setBounds(160, 100, 370, 30);

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack" }));
        jPanel2.add(cbjenis);
        cbjenis.setBounds(160, 140, 370, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 550, 220);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(null);

        Btn_Keluar.setBackground(new java.awt.Color(255, 204, 153));
        Btn_Keluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Keluar.setText("Keluar");
        Btn_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KeluarActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Keluar);
        Btn_Keluar.setBounds(40, 170, 110, 30);

        Btn_Simpan.setBackground(new java.awt.Color(255, 204, 153));
        Btn_Simpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Simpan.setText("Simpan");
        Btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SimpanActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Simpan);
        Btn_Simpan.setBounds(40, 10, 110, 30);

        Btn_Ubah.setBackground(new java.awt.Color(255, 204, 153));
        Btn_Ubah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Ubah.setText("Ubah");
        Btn_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UbahActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Ubah);
        Btn_Ubah.setBounds(40, 50, 110, 30);

        Btn_Bersihkan.setBackground(new java.awt.Color(255, 204, 153));
        Btn_Bersihkan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Bersihkan.setText("Bersihkan");
        Btn_Bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BersihkanActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Bersihkan);
        Btn_Bersihkan.setBounds(40, 90, 110, 30);

        Btn_Hapus.setBackground(new java.awt.Color(255, 204, 153));
        Btn_Hapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Hapus.setText("Hapus");
        Btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HapusActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Hapus);
        Btn_Hapus.setBounds(40, 130, 110, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(560, 90, 200, 220);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel8.setText("Pencarian Berdasarkan Kategori Makanan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 320, 300, 30);

        CbCariKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Makanan", "Minuman", "Baranglain" }));
        getContentPane().add(CbCariKategori);
        CbCariKategori.setBounds(300, 320, 100, 30);

        Btn_Cari.setBackground(new java.awt.Color(255, 204, 153));
        Btn_Cari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Cari.setText("Cari");
        Btn_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CariActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Cari);
        Btn_Cari.setBounds(430, 320, 80, 30);

        jPanel4.setBackground(new java.awt.Color(255, 102, 153));
        jPanel4.setLayout(null);

        Tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Packaging", "Harga"
            }
        ));
        Tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 510, 150);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 370, 550, 190);

        jPanel5.setBackground(new java.awt.Color(255, 102, 153));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(560, 370, 200, 190);

        jPanel6.setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 320, 760, 40);

        setBounds(0, 0, 775, 597);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SimpanActionPerformed
        // TODO add your handling code here:
        ctoko.SimpanData();
        ctoko.isiTable();
    }//GEN-LAST:event_Btn_SimpanActionPerformed

    private void Btn_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UbahActionPerformed
        // TODO add your handling code here:
        ctoko.Ubah();
        ctoko.isiTable();
    }//GEN-LAST:event_Btn_UbahActionPerformed

    private void Btn_BersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BersihkanActionPerformed
        // TODO add your handling code here:
        ctoko.Reset();
    }//GEN-LAST:event_Btn_BersihkanActionPerformed

    private void Btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HapusActionPerformed
        // TODO add your handling code here:
        ctoko.Hapus();
        ctoko.isiTable();
    }//GEN-LAST:event_Btn_HapusActionPerformed

    private void Btn_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Btn_KeluarActionPerformed

    private void Btn_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CariActionPerformed
        // TODO add your handling code here:
        ctoko.CariKategori();
        
    }//GEN-LAST:event_Btn_CariActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String user1 = login.user;
        txtadmin.setText(user1);
    }//GEN-LAST:event_formWindowOpened

    private void Tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel1MouseClicked
        // TODO add your handling code here:
        
        int baris = Tabel1.getSelectedRow();
        ctoko.isiField(baris);
    }//GEN-LAST:event_Tabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    
    public JTextField getTxtKode(){
        return txtkode;     
    }     
    public JTextField getTxtNama(){         
        return txtnama;     
    }     
    public JTextField getTxtHarga(){         
        return txtharga;     
    }     
    public JComboBox getCbKategori(){         
        return cbKategoriBrg;     
    }     
    public JComboBox getCbJenis(){         
        return cbjenis;     
    }     
    public JComboBox getCbCariKategori(){         
        return CbCariKategori;     
    }     
    public JButton getButtonHapus(){         
        return Btn_Hapus;     
    }          
    public JButton getButtonBersih(){         
        return Btn_Bersihkan;     
    }     
    public JButton getButtonSimpan(){         
        return Btn_Simpan;     
    }     
    public JButton getButtonUbah(){         
        return Btn_Ubah;     
    }     
    public JButton getButtonKeluar(){         
        return Btn_Keluar;     
    }     
    public JTable getTableData(){         
        return Tabel1;     
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Bersihkan;
    private javax.swing.JButton Btn_Cari;
    private javax.swing.JButton Btn_Hapus;
    private javax.swing.JButton Btn_Keluar;
    private javax.swing.JButton Btn_Simpan;
    private javax.swing.JButton Btn_Ubah;
    private javax.swing.JComboBox<String> CbCariKategori;
    private javax.swing.JTable Tabel1;
    private javax.swing.JComboBox<String> cbKategoriBrg;
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtadmin;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

    
}
